# Generated by Django 4.1.7 on 2023-03-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=150)),
                ('Cimage', models.ImageField(upload_to='')),
                ('Cdescription', models.TextField()),
            ],
        ),
    ]
