# Generated by Django 4.1.7 on 2023-03-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailymartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formdb',
            new_name='Categorydb',
        ),
    ]
