# Generated by Django 4.1.7 on 2023-03-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailymartapp', '0002_rename_formdb_categorydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.CharField(max_length=200)),
                ('pr_price', models.IntegerField()),
                ('pr_weight', models.IntegerField()),
                ('pr_image', models.FileField(upload_to='')),
                ('categories', models.CharField(max_length=200)),
            ],
        ),
    ]
