# Generated by Django 4.1.7 on 2023-03-31 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=55)),
                ('lname', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('saddress', models.CharField(max_length=300)),
                ('pcode', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('cemail', models.EmailField(max_length=254)),
                ('cphone', models.IntegerField()),
                ('cartid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.cart')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.registerb')),
            ],
        ),
    ]
